class JSONFileDoesNotExistException(message: String) : Exception(message)
class ResolvingInProgressConfigProviderException(message : String) : Exception(message)
class ResolvedFailureConfigProviderException(message : String) : Exception(message)
class ConfigWatcherAlreadyExistsException(message : String) : Exception(message)
class ConfigWatcherAlreadyStartedException(message : String) : Exception(message)
class ConfigWatcherIncompleteInitException(message : String) : Exception(message)
class ConfigWatcherNotRunningException(message : String) : Exception(message)